name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"   # trigger on every branch
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and push image with branch + sha tags
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile  
          push: true
          tags: |
            madnan19/creditsimulator-apps:${{ github.ref_name }}
            madnan19/creditsimulator-apps:${{ github.sha }}

      # 5. Push "latest" only if branch = master
      - name: Push Latest (master only)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: |
            madnan19/creditsimulator-apps:latest
